
from fastapi import FastAPI
from pydantic import BaseModel

import json


app = FastAPI(
    title="Planner AI API",
    version="1.0"
)


class Request(BaseModel):
    request: str



@app.get("/")
def home():

    return {
        "status":"Planner AI Online",
        "message":"Autonomous Planner Agent Running"
    }



@app.post("/plan")
def create_plan(data:Request):


    user_request = data.request


    plan = {

        "goal": user_request,

        "summary":
        "AI generated planning result",

        "tasks":[

            {
            "task":"Analyze user goal",
            "priority":"high",
            "estimated_minutes":60
            },

            {
            "task":"Create optimized plan",
            "priority":"high",
            "estimated_minutes":120
            },

            {
            "task":"Execute planned actions",
            "priority":"medium",
            "estimated_minutes":60
            }

        ],


        "notes":[
            "Generated by Planner AI Agent",
            "Ready for execution"
        ]

    }


    return plan
