
from fastapi import FastAPI
from pydantic import BaseModel
import json


app = FastAPI(
    title="Planner AI API",
    version="1.0"
)


class UserRequest(BaseModel):
    request: str



@app.get("/")
def home():
    return {
        "status":"Planner AI Online",
        "version":"1.0"
    }



@app.post("/plan")
def create_plan(data: UserRequest):

    user_input = data.request


    # AI connection placeholder
    # Replace with model inference function

    result = {
        "goal": user_input,
        "summary": "Generated by Planner AI",
        "tasks":[
            {
                "task":"Analyze user goal",
                "priority":"high",
                "estimated_minutes":60
            },
            {
                "task":"Create optimized plan",
                "priority":"high",
                "estimated_minutes":120
            }
        ],
        "notes":[
            "Planner AI API working"
        ]
    }


    return result
